#ifndef SENSORBRIDGE_IOCTL_H
#define SENSORBRIDGE_IOCTL_H

#include <linux/ioctl.h>

#define SENSORBRIDGE_MAGIC 'S'

#define SENSORBRIDGE_GET_STATUS \
    _IOR(SENSORBRIDGE_MAGIC, 1, int)

#define SENSORBRIDGE_SET_SAMPLE_RATE \
    _IOW(SENSORBRIDGE_MAGIC, 2, int)

#define SENSORBRIDGE_RESET \
    _IO(SENSORBRIDGE_MAGIC, 3)

#define SENSORBRIDGE_GET_READ_COUNT \
    _IOR(SENSORBRIDGE_MAGIC, 4, unsigned long)

#endif
